#include <stddef.h>

#include "c_codegen.h"
#include "diagnostics.h"
#include "function_registry.h"
#include "loop_ir.h"
#include "lower.h"
#include "pipeline_ir.h"
#include "pipeline_plan.h"
#include "simplify.h"
#include "string_builder.h"
#include "transpiler.h"

typedef enum
{
    RXJS_CALL_SOURCE,
    RXJS_CALL_OPERATOR,
    RXJS_CALL_TERMINAL,
    RXJS_CALL_RUNTIME
} RxJsCallKind;

typedef enum
{
    RXJS_ARG_NONE,
    RXJS_ARG_INT,
    RXJS_ARG_LONG,
    RXJS_ARG_VOID_PTR,
    RXJS_ARG_LIST_PTR,
    RXJS_ARG_OBSERVABLE_PTR,
    RXJS_ARG_QUERY_PTR,
    RXJS_ARG_SUBSCRIBER_FN,
    RXJS_ARG_BOOLEAN_FN,
    RXJS_ARG_MODIFIER_FN,
    RXJS_ARG_ACCUMULATOR_FN,
    RXJS_ARG_COMPARISON_FN,
    RXJS_ARG_FACTORY_FN,
    RXJS_ARG_VARIADIC_VOID_PTR,
    RXJS_ARG_VARIADIC_OBSERVABLE_PTR
} RxJsArgumentType;

typedef struct
{
    const char *name;
    RxJsCallKind kind;
    int min_arity;
    int max_arity;
    RxJsArgumentType return_type;
    RxJsArgumentType argument_types[4];
} RxJsFunctionSignature;

static const RxJsFunctionSignature k_rxjs_function_signatures[] = {
    { "range", RXJS_CALL_SOURCE, 2, 2, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_INT, RXJS_ARG_INT, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "of", RXJS_CALL_SOURCE, 1, -1, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_INT, RXJS_ARG_VARIADIC_VOID_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "empty", RXJS_CALL_SOURCE, 0, 0, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "never", RXJS_CALL_SOURCE, 0, 0, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "from", RXJS_CALL_SOURCE, 1, 1, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_LIST_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "interval", RXJS_CALL_SOURCE, 1, 1, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_LONG, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "timer", RXJS_CALL_SOURCE, 2, 2, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_LONG, RXJS_ARG_INT, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "defer", RXJS_CALL_SOURCE, 1, 1, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_FACTORY_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "zip", RXJS_CALL_SOURCE, 2, -1, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_INT, RXJS_ARG_VARIADIC_OBSERVABLE_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE } },

    { "map", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_MODIFIER_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "filter", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_BOOLEAN_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "scan", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_ACCUMULATOR_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "scanfrom", RXJS_CALL_OPERATOR, 2, 2, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_ACCUMULATOR_FN, RXJS_ARG_VOID_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "reduce", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_ACCUMULATOR_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "last", RXJS_CALL_OPERATOR, 0, 0, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "mergeMap", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "takeUntil", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_VOID_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "mapTo", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_VOID_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "buffer", RXJS_CALL_OPERATOR, 2, 2, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "take", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_INT, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "skip", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_INT, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "takeWhile", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_BOOLEAN_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "skipWhile", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_BOOLEAN_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "skipUntil", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_VOID_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "distinct", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_MODIFIER_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "distinctUntilChanged", RXJS_CALL_OPERATOR, 1, 1, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_MODIFIER_FN, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "throttleTime", RXJS_CALL_OPERATOR, 2, 2, RXJS_ARG_QUERY_PTR,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_INT, RXJS_ARG_NONE, RXJS_ARG_NONE } },

    { "pipe", RXJS_CALL_RUNTIME, 2, -1, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_INT, RXJS_ARG_QUERY_PTR, RXJS_ARG_NONE } },
    { "subscribe", RXJS_CALL_TERMINAL, 2, 2, RXJS_ARG_NONE,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_SUBSCRIBER_FN, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "create_observable", RXJS_CALL_RUNTIME, 0, 0, RXJS_ARG_OBSERVABLE_PTR,
      { RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "push_observable", RXJS_CALL_RUNTIME, 2, 2, RXJS_ARG_NONE,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_VOID_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE } },
    { "pop_all", RXJS_CALL_RUNTIME, 1, 1, RXJS_ARG_NONE,
      { RXJS_ARG_OBSERVABLE_PTR, RXJS_ARG_NONE, RXJS_ARG_NONE, RXJS_ARG_NONE } },
};

static const size_t k_rxjs_function_signature_count =
    sizeof(k_rxjs_function_signatures) / sizeof(k_rxjs_function_signatures[0]);
